spring:
  application:
    name: discovery-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

discovery:
  thresholds:
    minSpotVol24hUsd: 200000
    minPerpVol24hUsd: 5000000
    minDexVol24hUsd: 20000
    minDexTvlUsd: 100000
